sudo: false

language: python

python:
  - "2.7"
  - "3.6"

env:
  matrix:
    - MODE=dna
    - MODE=rna

before_script:
 - mkdir ~/.aws;
   echo "[default]" > ~/.aws/credentials;
   echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials;
   echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials;
   echo "[default]" > ~/.aws/config;
   echo "region = ${AWS_DEFAULT_REGION}" >> ~/.aws/config;
   echo "output = ${AWS_DEFAULT_OUTPUT}" >> ~/.aws/config;
 - wget https://github.com/aokad/ecsub/archive/master.zip;
   unzip master.zip;
   CURRENT=$(pwd);
   cd ecsub-master;
   python setup.py build install;
   cd ${CURRENT};

script:
  - python setup.py build install
  - genomon_pipeline_cloud ${MODE} test/sample_${MODE}.csv ${AWS_S3_BUCKET}/${MODE} test/param_${MODE}_ecsub.cfg --engine ecsub

notifications:
  emails:
    - aiokada@hgc.jp
  on_success: change
  on_failure: always

