language: python

matrix:
  include:
    - name: "Python 3.7 and dna"
      python: 3.7
      dist: xenial
      env:
        - MODE=dna
        - EXEC=1
    - name: "Python 3.7 and rna"
      python: 3.7
      dist: xenial
      env:
        - MODE=rna
        - EXEC=1
    - name: "Python 3.6 and dna"
      python: 3.6
      env:
        - MODE=dna
        - EXEC=2
    - name: "Python 3.6 and rna"
      python: 3.6
      env:
        - MODE=rna
        - EXEC=2
    - name: "Python 3.5 and dna"
      python: 3.5
      env:
        - MODE=dna
        - EXEC=0
    - name: "Python 3.5 and rna"
      python: 3.5
      env:
        - MODE=rna
        - EXEC=0
    - name: "Python 3.4 and dna"
      python: 3.4
      env:
        - MODE=dna
        - EXEC=0
    - name: "Python 3.4 and rna"
      python: 3.4
      env:
        - MODE=rna
        - EXEC=0
    - name: "Python 2.7 and dna"
      python: 2.7
      env:
        - MODE=dna
        - EXEC=0
    - name: "Python 2.7 and rna"
      python: 2.7
      env:
        - MODE=rna
        - EXEC=0

before_script:
 - mkdir ~/.aws;
   echo "[default]" > ~/.aws/credentials;
   echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials;
   echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials;
   echo "[default]" > ~/.aws/config;
   echo "region = ${AWS_DEFAULT_REGION}" >> ~/.aws/config;
   echo "output = ${AWS_DEFAULT_OUTPUT}" >> ~/.aws/config;
 - wget https://github.com/aokad/ecsub/archive/master.zip;
   unzip master.zip;
   CURRENT=$(pwd);
   cd ecsub-master;
   python setup.py build install;
   cd ${CURRENT};

script:
  - python setup.py build install
  - if [ ${EXEC} == 2 ] && [ ${MODE} == "dna" ]; then                genomon_pipeline_cloud ${MODE} test/sample_${MODE}_no_mutation.csv ${AWS_S3_BUCKET}/${MODE} test/param_${MODE}_ecsub_spot_grch38d1v1.cfg --engine ecsub; fi
  - if [ ${EXEC} == 2 ] && [ ${MODE} == "rna" ]; then travis_wait 60 genomon_pipeline_cloud ${MODE} test/sample_${MODE}.csv ${AWS_S3_BUCKET}/${MODE} test/param_${MODE}_ecsub_spot_grch38d1v1.cfg --engine ecsub; fi
  - if [ ${EXEC} == 1 ] && [ ${MODE} == "dna" ]; then                genomon_pipeline_cloud ${MODE} test/sample_${MODE}.csv ${AWS_S3_BUCKET}/${MODE} test/param_${MODE}_ecsub.cfg --engine ecsub; fi
  - if [ ${EXEC} == 1 ] && [ ${MODE} == "rna" ]; then travis_wait 60 genomon_pipeline_cloud ${MODE} test/sample_${MODE}.csv ${AWS_S3_BUCKET}/${MODE} test/param_${MODE}_ecsub.cfg --engine ecsub; fi
  - if [ ${EXEC} == 0 ]; then                                        genomon_pipeline_cloud ${MODE} test/sample_${MODE}.csv ${AWS_S3_BUCKET}/${MODE} test/param_${MODE}_ecsub.cfg --engine ecsub --dryrun; fi

notifications:
  emails:
    - aiokada@hgc.jp
  on_success: change
  on_failure: always

